#!/usr/bin/env bash

function domainInfo() {
    SUBDOMAINS=("www" "lb-01" "web-01" "web-02")
    if [ $# -eq 1 ]
    then
        for subdomain in "${SUBDOMAINS[@]}"; do
            RECORDTYPE="$(dig $subdomain.$1 | awk '/^'"$subdomain.$1"'\./ { getline; print $4 }')"
            DESTINATION="$(dig +short $subdomain.$1)"
            echo "The subdomain $subdomain is a $RECORDTYPE record and points to $DESTINATION"
        done
    elif [ $# -eq 2 ]
    then
        RECORDTYPE="$(dig $2.$1 | awk '/^'"$2.$1"'\./ { getline; print $4 }')"
        DESTINATION="$(dig +short $2.$1)"
        echo "The subdomain $2 is a $RECORDTYPE record and points to $DESTINATION"
    else
        echo "Usage: ./0-world_wide_web [DOMAIN] [optional SUBDOMAIN]"
    fi
}

if [ $# -eq 1 ]
then
    domainInfo $1
elif [ $# -eq 2 ]
then
    domainInfo $1 $2
else
    domainInfo
fi

