#!usr/bin/env bash
#installs nginx and configures it on a remote server

# Update system packages
apt-get -y update

# Install Nginx
apt-get -y install nginx

#Allow nginx
ufw allow 'Nginx HTTP'

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# start Nginx
systemct1 nginx start

