#!/bin/bash

# Update system packages
apt-get update

# Install Nginx
apt-get -y install nginx

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart

