#!/usr/bin/env bash
#configures a new ubuntu server with a custom http header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname
hostname=$(hostname)

# Configure Nginx
sudo sed -i 's/^http {/&\n    server_tokens off;/' /etc/nginx/nginx.conf
sudo bash -c "echo 'add_header X-Served-By $hostname;' > /etc/nginx/conf.d/custom_header.conf"
sudo systemctl restart nginx

