#!/usr/bin/env bash
#Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message
#the program should pause for 2 seconds

PID_FILE=/var/run/my_process.pid
LOG_FILE=/tmp/my_process

start_process() {
    if [ -f "$PID_FILE" ]; then
        echo "Process is already running with PID $(cat $PID_FILE)"
        exit 1
    fi
    nohup bash -c "while true; do echo 'I am alive!' >> $LOG_FILE; sleep 2; done" > /dev/null 2>&1 &
    echo $! > $PID_FILE
    echo "manage_my_process started"
}

stop_process() {
    if [ ! -f "$PID_FILE" ]; then
        echo "Process is not running"
        exit 1
    fi
    pid=$(cat $PID_FILE)
    kill $pid
    rm $PID_FILE
    echo "manage_my_process stopped"
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

